### ISSUE TITLE
Input tables for Melonnpan Train

### ISSUE THREAD

**Issue by Jalapenobadger** [biobakery/melonnpan#19]
Hi thanks for making this tool!

I am wondering where one can find appropriate tables for use with MelonnpanTrain? The data I am using is for Listeria samples, so I wouldn't expect any overlap from the human gut default tables, and indeed I am getting the error:  

"No common IDs found between training and test data. Execution halted!"

Is there somewhere these tables can be found, or made in way that they will input successfully? I cannot find anything anywhere describing the process or tools needed to make appropriate ones.

Thanks,
-Pete

**Comment by himelmallick** [comment]
Hi Pete - thanks for reaching out. Could you please check out the tutorial (Section 2.2)? The tutorial is located here: https://bitbucket.org/biobakery/biobakery/wiki/melonnpan. Let me know if that answers your question.

**Comment by himelmallick** [comment]
Hi Pete - thanks for reaching out. The format of the input data is described in the tutorial (see **Section 2.2**, https://bitbucket.org/biobakery/biobakery/wiki/melonnpan). Let me know if anything is unclear.

**Comment by Jalapenobadger** [comment]
Hi I‘ve reread that and read through the two papers it refers to and I still can’t seem to find how I would go about making the tables it requires. Is there somewhere for instance I can download a subsection of Uniref that is limited to my interest metabolites such that it will work here? Or is there some tool you guys used to format uniref90 to fit? Thanks,
-Pete

**Comment by himelmallick** [comment]
Hi Pete - I see what you mean now.  We used [HUMANn2](https://huttenhower.sph.harvard.edu/humann) for functional profiling. Also, for **MelonnPan-Train** (which trains a new model from user-provided paired metabolite and metagenomic functional data tables), you can use any functional profiling tool. Only for **MelonnPan-Predict** (which uses a pre-trained model based on HUMANn2), you need UniRef90 identifiers. Does it make sense?

**Comment by Jalapenobadger** [comment]
I’m still unsure but it sounds like I can somehow make the tables I need to train also from humann2 and maybe uniref. I am using humann2 for the predict side already. I’ll try to learn everything  I can about this before asking you more so I don’t take up too much of your time unnecessarily, thank you so much for getting back to me so quickly, it means a lot.

**Comment by himelmallick** [comment]
No worries. Drop me a line if you have any questions.

**Comment by Jalapenobadger** [comment]
Hi, sorry, I do have some more questions now.

So I looked back over everything in the Humann2 manual, looking for anything related to this:

> MelonnPan-Train workflow requires the following inputs:
> a table of metabolite relative abundances (samples in rows)
> a table of microbial sequence features' relative abundances (samples in rows)

and none of the 3 Humann2 outputs of gene families, pathway abundance, or pathway coverage seem to fit the bill, as none work at the level of the metabolites as individual units.

In all the tutorials and manuals I can find it says some variation of "functional profiles generated using Humann2," but I just cannot seem to find what script I should run on Humann2 or what inputs are necessary to create either of these Melonnpan train inputs. I feel there is some component that I'm totally missing.

So far, all I have been able to accomplish is producing the Humann2 output files I mentioned above from my metagenomic samples, but I know that I need to produce from somewhere the information on metabolite abundances which I wouldn't expect can be derived from my sequencing data alone. Is there some source that Humann2 can draw from and produce this data, or is it expected when using Melonnpan that the experimenter produces this on their own in addition to providing the sequencing data?

Thanks again,
-Pete

**Comment by himelmallick** [comment]
Hi Pete - HUMAnN2 is a functional profiling tool for microbial community shotgun sequencing, as you have already figured out. MelonnPan relies such as a functional table derived from HUMAnN2 or a similar system. However, in order to run **MelonnPan-Train**, you also need __measured metabolites for the same samples__, as you rightly indicated _'...when using Melonnpan ... the experimenter produces this on their own in addition to providing the sequencing data'_. If you only have functionally profiled metagenomes using HUMAnN2 in the form of UniRef90s, you can still use the **MelonnPan-Predict** workflow with the caveat that it relies on a pre-trained model from the human gut which may or may not resemble your environment of interest.

**Comment by himelmallick** [comment]
Hi Pete - HUMAnN2 is a functional profiling tool for microbial community shotgun sequencing, as you have already figured out. MelonnPan relies on such a functional table derived from HUMAnN2 or a similar system. However, in order to run **MelonnPan-Train**, you also need __measured metabolites for the same samples__, as you rightly indicated _'...when using Melonnpan ... the experimenter produces this on their own in addition to providing the sequencing data'_. If you only have functionally profiled metagenomes using HUMAnN2 in the form of UniRef90s, you can still use the **MelonnPan-Predict** workflow with the caveat that it relies on a pre-trained model from the human gut which may or may not resemble your environment of interest. I hope this clears up your confusion.

**Comment by Jalapenobadger** [comment]
Ah, okay, this is exactly what I was looking for. I fear we won't be able
to use it in the way we were hoping, but maybe I can find data from similar
previous research.
Thank you Mr Mallick!
-Pete
