### ISSUE TITLE
could you provide the metabolite file in the train module？

### ISSUE THREAD

**Issue by MonaLiu421** [biobakery/melonnpan#4]
could you provide the metabolite file in the train module？i wanna see the style of it，now，i dont have my own data，but i wanna research its usage，especially the how to train my data in the future。

**Comment by erawijantari** [comment]
Hi Melonnpan developer,
I also want to request the metabolite file in the train module.
Currently I have both metagenomic (annotated by HUMAnN2 based on Uniref90) and metabolomic concentration data. First, I try to run the `MelonnPan-Predict` on my metagenomic data to make sure it can be run using my data and it was perfectly fine.
The problem appears when I try the `MelonnPan-Train`.

First error was
```
Error in melonnpan::melonnpan.train(metab = metab, metag = metag, alpha = alpha,  : 
 All measurements should be normalized to proportions.
Execution halted
```

I have checked my metagenome and metabolome input and it was already normalized to proportion. So, I looked at the code and solved it by adding these two lines before line 57 in the `R/melonnpan_train.R`, to read the files into dataframe, Please check if it appropriate or not.

```
metag<-data.frame(readTable(metag))
metab<-data.frame(readTable(metab))
```
Later I found another error.

```
Error in ztransform(formula, data, family) : trait is binary
Calls: <Anonymous> -> apply -> FUN -> ztransform
Execution halted
```
Do you have any idea to solve this issue? For your information, I run it under the SGE computer using 4 cores. 

Additionally, I actually concern about the format needed by Melonnpan for `metab` input.I just followed the format given in the publication `(https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-019-10927-1/MediaObjects/41467_2019_10927_MOESM4_ESM.xlsx)`. However, instead of using the compound name as in Human Metabolome Database (HMDB), I used the compound ID and name listed by KEGG compound identifier. Could you provide more explanation on how to correctly provide the input file for metabolome data.

**Comment by himelmallick** [comment]
Hi @MonaLiu421 and @erawijantari - thanks for trying out the MelonnPan-Train module. Please keep an eye out this week for an updated tutorial at https://bitbucket.org/biobakery/biobakery/wiki/melonnpan.

**Comment by himelmallick** [comment]
Hi @erawijantari - regarding your other issue, MelonnPan is agnostic to the annotation of individual metabolites or microbial sequence features, and therefore, using the KEGG IDs for the metabolites should be fine. It looks like you have one or more binary features in your metagenomes which is causing the error as the rank-based inverse normal transformation is invalid for features with only a few unique values. Could you please let me know if you still get the error once you carefully remove the metagenomic features with only a handful of unique values?

**Comment by himelmallick** [comment]
Additionally, I will recommend doing some basic independent filtering (e.g. based on prevalence or abundance or variance) before running the MelonnPan-Train module which will significantly reduce the computational burden during the training process.

**Comment by himelmallick** [comment]
Hi @erawijantari and @MonaLiu421 - the tutorial has now been updated to include more information on the MelonnPan-Train module. Should you need any further information, please do not hesitate to contact me.

**Comment by MonaLiu421** [comment]
ok，i can do it，thanks a million.but i have a confusion,why do i get the different result when use the same data？

**Comment by himelmallick** [comment]
Hi @MonaLiu421 - it has been addressed here: https://github.com/biobakery/melonnpan/issues/5. Please install the most updated version which should have fixed the randomness issue of the cv.glmnet function. Let me know it not. Many thanks!
